version: '3'

tasks:
  coverage:
    cmds:
      - go test -short -count=1 -race -coverprofile=coverage.out ./...
      - go tool cover -html=coverage.out
      - rm coverage.out
  lint:
    cmd: pre-commit
  test:
    cmd: go test -v --parallel 8 -race -count=1 ./...
  test20:
    cmd: go test -v --parallel 8 -race -count=20 ./...
  swag-gen:
    cmd: swag init -g ./cmd/http.go -o docs/
  run-http:
    cmds:
      - swag init -g ./cmd/http.go -o docs/
      - go run main.go http
