version: '3'

tasks:
  set-up:
    cmds:
      - brew install pre-commit
      - GOPROXY=https://proxy.golang.org,direct go get
      - GOPROXY=https://proxy.golang.org,direct go install github.com/swaggo/swag/cmd/swag@latest
  coverage:
    cmds:
      - go test -short -count=1 -race -coverprofile=coverage.out ./...
      - go tool cover -html=coverage.out
      - rm coverage.out
  lint:
    cmd: pre-commit
  test:
    cmd: go test -v --parallel 8 -race -count=1 ./...
  test20:
    cmd: go test -v --parallel 8 -race -count=20 ./...
  swag-gen:
    cmd: swag init -g ./cmd/http.go -o docs/
  run-local:
    cmds:
      - docker-compose -f docker-compose.local.yml up -d
      - sleep 7
      - swag init -g ./cmd/http.go -o docs/
      - go run main.go http
  http-local:
    cmds:
      - go install github.com/mitranim/gow@latest
      - swag init -g ./cmd/http.go -o docs/
      - gow run main.go http
  db-local:
    cmd: docker-compose -f docker-compose.local.yml up postgres
  download:
    cmds:
      - GOPROXY=https://proxy.golang.org,direct go get
