// Code generated by goro;

package notifyservice

// This file was generated by the goro tool.

type userRepo interface {
	// TODO: define interface to inject a service or an adapter
}

type proposalRepo interface {
	// TODO: define interface to inject a service or an adapter
}

type Service struct {
	userRepo userRepo

	proposalRepo proposalRepo
}

func NewService(userRepo userRepo, proposalRepo proposalRepo) *Service {
	return &Service{

		userRepo: userRepo,

		proposalRepo: proposalRepo,
	}
}
