// Code generated by goro;

package authservice

import (
	"context"
	"github.com/google/uuid"
	e "notify/internal/entity"
	"notify/pkg/logger"
)

// This file was generated by the goro tool.

type userRepo interface {
	Create(ctx context.Context, user *e.User) (*e.UserDB, error)
	GetAll(ctx context.Context) (*[]e.UserDB, error)
	GetByID(ctx context.Context, id uuid.UUID) (*e.UserDB, error)
	GetByLogin(ctx context.Context, login string) (*e.UserDB, error)
	UpdateCommonInfoByID(c context.Context, id uuid.UUID, data e.UserCommonInfo) (*e.UserDB, error)
	GetByEmail(ctx context.Context, email string) (*e.UserDB, error)
}

type Service struct {
	userRepo userRepo
	log      logger.Logger
}

func NewService(userRepo userRepo) *Service {
	return &Service{
		userRepo: userRepo,
	}
}
