// Code generated by goro;

package authservice

import "notify/internal/entity"

// This file was generated by the goro tool.

type userRepo interface {
	GetByLogin(login string) (entity.User, error)
	Create(user *entity.User) (entity.User, error)
	CreateWithDetails(info entity.UserCommonInfo, cred entity.UserCred) (entity.User, error)
}

type Service struct {
	userRepo userRepo
}

func NewService(userRepo userRepo) *Service {
	return &Service{
		userRepo: userRepo,
	}
}
