basePath: /api/
definitions:
  entity.GetUserInput:
    properties:
      user_id:
        type: string
      user_login:
        type: string
    type: object
  entity.User:
    properties:
      cred:
        $ref: '#/definitions/entity.UserCred'
      info:
        $ref: '#/definitions/entity.UserCommonInfo'
    type: object
  entity.UserCommonInfo:
    properties:
      birthday:
        type: string
      email:
        type: string
      name:
        type: string
      role:
        $ref: '#/definitions/entity.UserRole'
    required:
    - email
    - name
    type: object
  entity.UserCred:
    properties:
      login:
        type: string
      password:
        type: string
    required:
    - login
    - password
    type: object
  entity.UserRole:
    enum:
    - admin
    - service
    - person
    type: string
    x-enum-varnames:
    - Admin
    - Service
    - Person
  http.ErrForResp:
    properties:
      code:
        type: string
      message:
        type: string
    type: object
  http.Resp-entity_UserCommonInfo:
    properties:
      message:
        type: string
      meta:
        type: string
      result:
        $ref: '#/definitions/entity.UserCommonInfo'
    type: object
  http.RespErr:
    properties:
      error:
        $ref: '#/definitions/http.ErrForResp'
      meta:
        type: string
    type: object
info:
  contact:
    email: kalinindima123@yandex.ru
    name: Dima Kalinin
    url: https://dimdimi4-and-fixiki.github.io/dima-portal/
  description: Service for sending notifications to users
  title: Notifier API
  version: 0.0.1
paths:
  /admin/get_user/:
    post:
      consumes:
      - application/json
      description: Return user by user id or user login
      parameters:
      - description: no_comm
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/entity.GetUserInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/http.Resp-entity_UserCommonInfo'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/http.RespErr'
      summary: get user info
      tags:
      - Admin
  /admin/register_user/:
    post:
      consumes:
      - application/json
      description: Register new user with user details
      parameters:
      - description: User details
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/entity.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/http.Resp-entity_UserCommonInfo'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/http.RespErr'
      summary: Register new user
      tags:
      - Admin
swagger: "2.0"
