basePath: /api/
definitions:
  entity.AuthData:
    properties:
      login:
        type: string
      password:
        type: string
    type: object
  entity.CreateServiceReq:
    properties:
      login:
        type: string
      service_name:
        type: string
    type: object
  entity.GetUserInput:
    properties:
      user_id:
        type: string
      user_login:
        type: string
    type: object
  entity.JWTString:
    properties:
      expires_at:
        type: string
      token:
        type: string
    type: object
  entity.ProjectProposal:
    properties:
      description:
        type: string
      email:
        type: string
      reason:
        type: string
      title:
        type: string
    type: object
  entity.ReqWithApiToken-entity_ProjectProposal:
    properties:
      auth:
        $ref: '#/definitions/entity.AuthData'
      data:
        $ref: '#/definitions/entity.ProjectProposal'
    type: object
  entity.ReqWithApiToken-entity_User:
    properties:
      auth:
        $ref: '#/definitions/entity.AuthData'
      data:
        $ref: '#/definitions/entity.User'
    type: object
  entity.ServiceCred:
    properties:
      api_key:
        type: string
      login:
        type: string
    type: object
  entity.ServiceUser:
    properties:
      common_info:
        $ref: '#/definitions/entity.ServiceUserCommonInfo'
      cred:
        $ref: '#/definitions/entity.ServiceCred'
    type: object
  entity.ServiceUserCommonInfo:
    properties:
      name:
        type: string
    required:
    - name
    type: object
  entity.User:
    properties:
      cred:
        $ref: '#/definitions/entity.UserCred'
      info:
        $ref: '#/definitions/entity.UserCommonInfo'
    type: object
  entity.UserCommonInfo:
    properties:
      birthday:
        type: string
      email:
        type: string
      name:
        type: string
      role:
        $ref: '#/definitions/entity.UserRole'
    required:
    - name
    type: object
  entity.UserCred:
    properties:
      login:
        type: string
      password:
        type: string
    required:
    - login
    - password
    type: object
  entity.UserRole:
    enum:
    - admin
    - service
    - person
    type: string
    x-enum-varnames:
    - Admin
    - Service
    - Person
  http.ErrForResp:
    properties:
      code:
        type: string
      message:
        type: string
    type: object
  http.Resp-entity_ServiceUser:
    properties:
      message:
        type: string
      meta:
        type: string
      result:
        $ref: '#/definitions/entity.ServiceUser'
    type: object
  http.Resp-entity_UserCommonInfo:
    properties:
      message:
        type: string
      meta:
        type: string
      result:
        $ref: '#/definitions/entity.UserCommonInfo'
    type: object
  http.Resp-v1_respDecodeJWT:
    properties:
      message:
        type: string
      meta:
        type: string
      result:
        $ref: '#/definitions/v1.respDecodeJWT'
    type: object
  http.Resp-v1_respRegisterUser:
    properties:
      message:
        type: string
      meta:
        type: string
      result:
        $ref: '#/definitions/v1.respRegisterUser'
    type: object
  http.Resp-v1_respSendProposal:
    properties:
      message:
        type: string
      meta:
        type: string
      result:
        $ref: '#/definitions/v1.respSendProposal'
    type: object
  http.RespErr:
    properties:
      error:
        $ref: '#/definitions/http.ErrForResp'
      meta:
        type: string
    type: object
  v1.req:
    properties:
      token:
        type: string
    type: object
  v1.respDecodeJWT:
    properties:
      user_login:
        type: string
      user_role:
        $ref: '#/definitions/entity.UserRole'
    type: object
  v1.respRegisterUser:
    properties:
      jwt:
        $ref: '#/definitions/entity.JWTString'
      user:
        $ref: '#/definitions/entity.UserCommonInfo'
    type: object
  v1.respSendProposal:
    type: object
info:
  contact:
    email: kalinindima123@yandex.ru
    name: Dima Kalinin
    url: https://dimdimi4-and-fixiki.github.io/dima-portal/
  description: Service for sending notifications to users
  title: Notifier API
  version: 0.0.1
paths:
  /admin/get_user/:
    post:
      consumes:
      - application/json
      description: Return user by user id or user login
      parameters:
      - description: no_comm
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/entity.GetUserInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/http.Resp-entity_UserCommonInfo'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/http.RespErr'
      summary: get user info
      tags:
      - Admin
  /admin/register_service/:
    post:
      consumes:
      - application/json
      description: Register new user with user details
      parameters:
      - description: Service details
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/entity.CreateServiceReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/http.Resp-entity_ServiceUser'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/http.RespErr'
      summary: Register new service
      tags:
      - Admin
  /admin/register_user/:
    post:
      consumes:
      - application/json
      description: Register new user with user details
      parameters:
      - description: User details
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/entity.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/http.Resp-entity_UserCommonInfo'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/http.RespErr'
      summary: Register new user
      tags:
      - Admin
  /v1/decode_jwt/:
    post:
      consumes:
      - application/json
      description: Decode JWT token
      parameters:
      - description: JWT token
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/v1.req'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/http.Resp-v1_respDecodeJWT'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/http.RespErr'
      summary: View what's inside your JWT token
      tags:
      - v1
  /v1/register_user/:
    post:
      consumes:
      - application/json
      description: Register new user with user details
      parameters:
      - description: Auth data and User details
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/entity.ReqWithApiToken-entity_User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/http.Resp-v1_respRegisterUser'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/http.RespErr'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/http.RespErr'
      summary: Register new user with role person
      tags:
      - v1
  /v1/send_proposal/:
    post:
      consumes:
      - application/json
      description: Send email with proposal text to user and owner
      parameters:
      - description: Project proposal data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/entity.ReqWithApiToken-entity_ProjectProposal'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/http.Resp-v1_respSendProposal'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/http.RespErr'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/http.RespErr'
      summary: Send email with proposal to user and owner
      tags:
      - v1
swagger: "2.0"
